import { StyleSheet } from "react-native-web";
import colors from "./colors";

export default global = StyleSheet.create({
  pageContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginTop: 15,
  },
  headerMenu: {
    flex: 0.1,
    backgroundColor: colors.parentMenuBorder,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  headerText: {
    color: "black",
    fontSize: 35,
    fontWeight: "bold",
    textAlign: "center",
  },
  refreshButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    margin: 10,
  },
  leftMenu: {
    flex: 1,
    flexDirection: "col",
    backgroundColor: colors.parentMenuBorder,
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 5,
    marginLeft: 15,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  rightContainer: {
    flex: 1,
    flexDirection: "col",
    justifyContent: "space-evenly",
    marginLeft: 15,
    marginRight: 15,
  },
  rightMenu: {
    flex: 1,
    flexDirection: "col",
    backgroundColor: colors.borderRightColor,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  ArrowView: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: colors.borderRightColor,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  ButtonList: {
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.fontColor,
    textAlign: "left",
    borderRadius: 5,
    height: 50,
    margin: 5,
    paddingLeft: 10,
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  ButtonText: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.fontColor,
  },
  AddRequestButton: {
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    borderColor: colors.borderRightColor,
    backgroundColor: colors.primary,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.secondary,
    margin: 5,
    paddingLeft: 10,
  },
  ListView: {
    flex: 1,
    marginTop: 40,
  },
  icon: {
    position: "absolute",
    right: 10,
    flex: 1,
  },
  smallButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  smallButtonText: {
    color: colors.smallButtonTextColor,
    fontSize: 12,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
  },
  ArrowButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  ModalView: {
    flex:1,
    alignItems:"center",
    justifyContent:"center"
  },
  ModalContainer: {
    flex: 0.7,
    flexDirection: "col",
    width: "70%",
    shadowRadius: 20,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: colors.primary,
    backgroundColor: colors.secondary,
  },
  TopModalView: {
    flex: 1,
  },
  BottomModalView: {
    flex: 1,
    justifyContent: "flex-end",
  },
  buttonClose: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    height: 50,
  },
  errorMsg: {
    color: "red",
    fontSize: 12,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
  }
});
