import { StyleSheet } from "react-native-web";
import colors from "./colors";

export default global = StyleSheet.create({
  pageContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginTop: 15,
  },
  LoginPageContainer: {
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  LoginContainer: {
    flex: 1,
    width: "25%",
    margin: 5,
    backgroundColor: colors.secondary,
    justifyContent: "center",
  },
  LoginButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: colors.primary,
    margin: 10,
  },
  headerMenu: {
    flex: 0.1,
    backgroundColor: colors.parentMenuBorder,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  LoginHeaderText: {
    fontSize: 18,
    lineHeight: 25,
    letterSpacing: 0.5,
    color: colors.primary,
    fontWeight: "bold",
    marginTop: 5,
  },
  headerText: {
    color: "black",
    fontSize: 35,
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "capitalize"
  },
  refreshButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    margin: 10,
  },
  leftMenu: {
    flex: 1,
    flexDirection: "col",
    backgroundColor: colors.parentMenuBorder,
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 5,
    marginLeft: 15,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  rightContainer: {
    flex: 1,
    flexDirection: "col",
    justifyContent: "space-evenly",
    marginLeft: 15,
    marginRight: 15,
  },
  rightMenu: {
    flex: 1,
    flexDirection: "col",
    backgroundColor: colors.borderRightColor,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  ArrowView: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: colors.borderRightColor,
    borderRadius: 5,
    marginBottom: 15,
    borderWidth: 0,
    borderColor: colors.primary,
  },
  ButtonList: {
    flexDirection: "row",
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.fontColor,
    textAlign: "left",
    alignItems: "center",
    borderRadius: 5,
    height: 50,
    margin: 5,
    paddingRight: 10,
    paddingLeft: 10,
    justifyContent: "space-between",
    backgroundColor: colors.primary,
  },
  LoginButtonText: {
    fontSize: 12,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: colors.secondary,
  },
  ButtonText: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.fontColor,
  },
  TextInputStyle: { //CHILD
    borderColor: colors.primary,
    borderWidth: 2,
    borderRadius: 3,
    height: 50,
    width: 150,
    marginRight: 10,
    textAlign: "center",
    fontWeight: "bold",
  },
  TextInputInModal: {
    borderColor: colors.primary,
    borderWidth: 1,
    height: 35,
    padding: 15,
  },
  ListRightButtons: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    marginLeft: 15,
  },
  IconButton: {
    marginLeft: 10,
  },
  AddRequestButton: {
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    borderColor: colors.borderRightColor,
    backgroundColor: colors.primary,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: colors.secondary,
    margin: 5,
    paddingLeft: 10,
  },
  ListView: {
    flex: 1,
    marginTop: 40,
  },
  icon: {
    position: "absolute",
    right: 10,
    flex: 1,
  },
  smallButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  smallButtonText: {
    color: colors.smallButtonTextColor,
    fontSize: 12,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
  },
  ArrowButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
   CheckboxContainer: {
    flex: 1,
  },
  CheckboxSection: {
    flexDirection: "row",
    alignItems: "center",
  },
  Checkbox: {
    margin: 8,
  },
  ModalView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  ModalContainer: {
    flex: 0.8,
    flexDirection: "col",
    width: "70%",
    shadowRadius: 20,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: colors.primary,
    backgroundColor: colors.secondary,
  },
  ModalConfigContainer: {
    flex: 0.4,
    flexDirection: "col",
    width: "40%",
    shadowRadius: 20,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: colors.primary,
    backgroundColor: colors.secondary,
  },
  TopModalView: {
    flex: 1,
  },
  BottomModalView: {
    flexDirection: "row",
  },
  buttonClose: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRightColor: "white",
    borderLeftColor: "white",
    backgroundColor: colors.primary,
    height: 50,
  },
  TextInput: {
    height: 50,
    flex: 1,
    padding: 10,
    paddingRight: 40,
  },
  SendButton: {
    height: 50,
    width: 150,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  errorMsg: {
    color: "red",
    fontSize: 12,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
  },
});
